import React from "react";
import Text from "../../../../elements/Text";


const RandomGeneratingAlgorithm = {
  data: {
    title: "난수 생성 알고리즘",
    createdate: "2024-11-28",
    editdate: "2024-11-28",
    category: ["개발", "Python"],
    dir: "/development/python/random-generating-algorithm",
    content: (
      <div>
        <h3>들어가는 글</h3>
        <p>학교 과제용으로 제작한 난수 생성 알고리즘입니다.</p>

        <h3>코드</h3>
        <h3>main.py</h3>
        <div className="codeblock-body">
          <div className="codeblock-text">
<div>
<span className="code-magenta">{"import"}</span>&nbsp;<span className="code-white">{"matplotlib"}</span><br></br>
<span className="code-white">{"matplotlib"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"use"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"Qt5Agg\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-magenta">{"from"}</span>&nbsp;<span className="code-white">{"matplotlib"}</span>&nbsp;<span className="code-magenta">{"import"}</span>&nbsp;<span className="code-white">{"pyplot"}</span>&nbsp;<span className="code-magenta">{"as"}</span>&nbsp;<span className="code-white">{"plt"}</span><br></br>
<span className="code-magenta">{"import"}</span>&nbsp;<span className="code-white">{"time"}</span><br></br>
<br></br>
<br></br>
<span className="code-white">{"rng"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1000"}</span>&nbsp;<span className="code-gray">{"# from 1 to rng"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"SplitDigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"num"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-gray">{"# 자릿수 분리"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"l"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-blue">{"]"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-purple">{"str"}</span><span className="code-blue">{"("}</span><span className="code-white">{"num"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"l"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-purple">{"int"}</span><span className="code-blue">{"("}</span><span className="code-white">{"i"}</span><span className="code-blue">{")"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-white">{"l"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"checkRange"}</span><span className="code-blue">{"("}</span><span className="code-white">{"s"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"e"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"num"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"s"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span>&nbsp;<span className="code-white">{"num"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span>&nbsp;<span className="code-white">{"e"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"class"}</span>&nbsp;<span className="code-white">{"Fibonacci"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"__init__"}</span><span className="code-blue">{"("}</span><span className="code-white">{"self"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-lightgreen">{"0"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-gray">{"# 성능 향상을 위해 생성된 값을 저장"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"makefib"}</span><span className="code-blue">{"("}</span><span className="code-white">{"self"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"index"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-purple">{"len"}</span><span className="code-blue">{"("}</span><span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span>&nbsp;<span className="code-white">{"index"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-gray">{"# fib 리스트의 길이가 index 보다 작으면 len(fib) - 1이 index와 같아질 때까지 append"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-purple">{"range"}</span><span className="code-blue">{"("}</span><span className="code-white">{"index"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"None"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{"["}</span><span className="code-white">{"index"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"None"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-gray">{"# 만약 Fibonacci(index)의 값이 fib에 있으면 그 값을 반환"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{"["}</span><span className="code-white">{"index"}</span><span className="code-blue">{"]"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"index"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{"["}</span><span className="code-white">{"index"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"index"}</span>&nbsp;<span className="code-gray">{"# 생성된 값을 fib에 저장"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-white">{"index"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{"["}</span><span className="code-white">{"index"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"makefib"}</span><span className="code-blue">{"("}</span><span className="code-white">{"index"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"2"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"makefib"}</span><span className="code-blue">{"("}</span><span className="code-white">{"index"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-gray">{"# 생성된 값을 fib에 저장"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-white">{"self"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"fib"}</span><span className="code-blue">{"["}</span><span className="code-white">{"index"}</span><span className="code-blue">{"]"}</span><br></br>
<br></br>
<span className="code-white">{"class"}</span>&nbsp;<span className="code-white">{"Random"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"std"}</span><span className="code-blue">{"("}</span><span className="code-white">{"self"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"seed"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-gray">{"# 1-rng 중 하나를 무작위로 반환하는 함수 | seed의 값이 같으면 반환값도 같음"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"fib"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"Fibonacci"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"fib"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"makefib"}</span><span className="code-blue">{"("}</span><span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"7"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"s"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"SplitDigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"seed"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-gray">{"# seed를 자릿수를 기준으로 분리하여 리스트 생성"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-white">{"s"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"continue"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"round"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-white">{"i"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-lightgreen">{"32"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"*"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"10"}</span>&nbsp;<span className="code-lightyellow">{"*"}</span><span className="code-lightyellow">{"*"}</span>&nbsp;<span className="code-purple">{"len"}</span><span className="code-blue">{"("}</span><span className="code-white">{"s"}</span><span className="code-blue">{")"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ret"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span><span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span>&nbsp;<span className="code-lightyellow">{"%"}</span>&nbsp;<span className="code-white">{"rng"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ret"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span><span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"%"}</span>&nbsp;<span className="code-white">{"rng"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-purple">{"int"}</span><span className="code-blue">{"("}</span><span className="code-white">{"ret"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"usetime"}</span><span className="code-blue">{"("}</span><span className="code-white">{"self"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"seed"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-white">{"int"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span>&nbsp;<span className="code-gray">{"# Random()의 s를 현재 시각으로 변경 -> 값이 매번 달라짐"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"fib"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"Fibonacci"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"key"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"time"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"time"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-gray">{"# 현재 시각"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"fib"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"makefib"}</span><span className="code-blue">{"("}</span><span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"7"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"s"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"SplitDigit"}</span><span className="code-blue">{"("}</span><span className="code-purple">{"int"}</span><span className="code-blue">{"("}</span><span className="code-white">{"key"}</span><span className="code-blue">{")"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-gray">{"# 현재 시각을 자릿수를 기준으로 분리하여 리스트 생성"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-white">{"s"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"continue"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"round"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-white">{"i"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-lightgreen">{"32"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"*"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"10"}</span>&nbsp;<span className="code-lightyellow">{"*"}</span><span className="code-lightyellow">{"*"}</span>&nbsp;<span className="code-purple">{"len"}</span><span className="code-blue">{"("}</span><span className="code-white">{"s"}</span><span className="code-blue">{")"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ret"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span><span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span>&nbsp;<span className="code-lightyellow">{"%"}</span>&nbsp;<span className="code-white">{"rng"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ret"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span>&nbsp;<span className="code-lightyellow">{"/"}</span><span className="code-lightyellow">{"/"}</span>&nbsp;<span className="code-white">{"seed"}</span>&nbsp;<span className="code-lightyellow">{"%"}</span>&nbsp;<span className="code-white">{"rng"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-purple">{"int"}</span><span className="code-blue">{"("}</span><span className="code-white">{"ret"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
<br></br>
<span className="code-gray">{"# 피보나치 수열의 n번째 수가 y, n이 x"}</span><br></br>
<span className="code-white">{"x"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-blue">{"]"}</span><br></br>
<span className="code-white">{"y"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-blue">{"]"}</span><br></br>
<span className="code-white">{"attempt"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"543"}</span><br></br>
<span className="code-white">{"success"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><br></br>
<span className="code-white">{"rand"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"Random"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"start"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<span className="code-white">{"end"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"300"}</span><br></br>
<br></br>
<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-purple">{"range"}</span><span className="code-blue">{"("}</span><span className="code-lightgreen">{"1"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"attempt"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"x"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"i"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"y"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"rand"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"std"}</span><span className="code-blue">{"("}</span><span className="code-white">{"i"}</span><span className="code-blue">{")"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-purple">{"checkRange"}</span><span className="code-blue">{"("}</span><span className="code-white">{"start"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"end"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"y"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"success"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
<br></br>
<span className="code-gray">{"# 그래프 생성"}</span><br></br>
<span className="code-white">{"plt"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"plot"}</span><span className="code-blue">{"("}</span><span className="code-white">{"x"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"y"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"ob\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"plt"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"title"}</span><span className="code-blue">{"("}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"f"}</span><span className="code-orange">{"\"Chance of choosing {end}({start}-{end}) in {rng}: {round(success / attempt, 3)}"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{""}</span><span className="code-blue">{"\\"}</span><br></br>
<span className="code-orange">{"    (The chance has to be {round(end / rng, 3)} theoretically.)\""}</span><br></br>
<span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"plt"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"axhline"}</span><span className="code-blue">{"("}</span><span className="code-white">{"y"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"start"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"xmin"}</span><span className="code-lightyellow">{"="}</span><span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"xmax"}</span><span className="code-lightyellow">{"="}</span><span className="code-white">{"attempt"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"color"}</span><span className="code-lightyellow">{"="}</span><span className="code-orange">{"\"red\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"plt"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"axhline"}</span><span className="code-blue">{"("}</span><span className="code-white">{"y"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"end"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"xmin"}</span><span className="code-lightyellow">{"="}</span><span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"xmax"}</span><span className="code-lightyellow">{"="}</span><span className="code-white">{"attempt"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"color"}</span><span className="code-lightyellow">{"="}</span><span className="code-orange">{"\"red\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"plt"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"show"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span>
</div>
          </div>
        </div>
      </div>
    )
  },
  
  page: function () {
    return (
      <Text title={RandomGeneratingAlgorithm.data.title} createdate={RandomGeneratingAlgorithm.data.createdate} editdate={RandomGeneratingAlgorithm.data.editdate} content={RandomGeneratingAlgorithm.data.content} />
    );
  }  
}

export default RandomGeneratingAlgorithm;