import React from "react";
import Text from "../../../../elements/Text";


const PythonCodeHighlighter = {
  data: {
    title: "파이썬 코드 하이라이터",
    createdate: "2024-11-28",
    editdate: "2024-11-28",
    dir: "/development/python/python-code-highlighter",
    content: (
      <div>
        <h3>들어가는 글</h3>
        <p>파이썬 코드 하이라이터입니다.</p>
        <p><a className="link" href="/development/c/c-code-highlighter">C 코드 하이라이터</a>를 파이썬으로 구현하고 그에 맞게 다듬은 것입니다.</p>
        <p>세부 사항은 C 코드 하이라이터와 같으니 참고하세요.</p>

        <h3>코드</h3>
        <h3>main.py</h3>
        <div className="codeblock-body">
          <div className="codeblock-text">
<div>
<span className="code-magenta">{"from"}</span>&nbsp;<span className="code-white">{"enum"}</span>&nbsp;<span className="code-magenta">{"import"}</span>&nbsp;<span className="code-white">{"IntEnum"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"auto"}</span><br></br>
<br></br>
<br></br>
<span className="code-white">{"indentSize"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"4"}</span>&nbsp;<span className="code-gray">{"# Set indent size(spaces per tab) as you want"}</span><br></br>
<br></br>
<span className="code-white">{"class"}</span>&nbsp;<span className="code-purple">{"Tag"}</span><span className="code-blue">{"("}</span><span className="code-white">{"IntEnum"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Zero"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Ident"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Func"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Int"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Str"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Paren"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Etc"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Keyword"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Space"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Break"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Comment"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"Escape"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"auto"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"isalpha"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"ord"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"65"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"90"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"97"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"122"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"isdigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"ord"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-lightgreen">{"48"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"57"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"isparen"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"paren"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\"(){}[]\""}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-white">{"paren"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"char"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"i"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"ispunct"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"ord"}</span><span className="code-blue">{"("}</span><span className="code-white">{"char"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"33"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"47"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"58"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"64"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"91"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"96"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-lightgreen">{"123"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"ascii"}</span>&nbsp;<span className="code-lightyellow">{"<"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"126"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"checkKeyword"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"keyword"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-orange">{"\"break\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"case\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"continue\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"else\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"for\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"if\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"return\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"while\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"with\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"as\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"import\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"from\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"in\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"try\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"except\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"elif\""}</span><span className="code-blue">{"]"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-white">{"keyword"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"str"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"i"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<span className="code-white">{"def"}</span>&nbsp;<span className="code-purple">{"checkBool"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"boolean"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-orange">{"\"and\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"or\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"not\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"True\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"False\""}</span><span className="code-blue">{"]"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-white">{"boolean"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"str"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"i"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"return"}</span>&nbsp;<span className="code-lightyellow">{"False"}</span><br></br>
<br></br>
<br></br>
<span className="code-white">{"fname"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"input"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"File name: \""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-magenta">{"try"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"open"}</span><span className="code-blue">{"("}</span><span className="code-white">{"fname"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"r\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"encoding"}</span><span className="code-lightyellow">{"="}</span><span className="code-orange">{"\"utf-8\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-magenta">{"except"}</span>&nbsp;<span className="code-white">{"FileNotFoundError"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-purple">{"print"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"No file name \'"}</span><span className="code-blue">{"{"}</span><span className="code-white">{"fname"}</span><span className="code-blue">{"}"}</span><span className="code-orange">{"\'.\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-purple">{"exit"}</span><span className="code-blue">{"("}</span><span className="code-lightgreen">{"0"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
<span className="code-white">{"str"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\"\""}</span><br></br>
<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"line"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"readline"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-lightyellow">{"not"}</span>&nbsp;<span className="code-white">{"line"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"break"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"str"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"line"}</span><br></br>
<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"close"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-purple">{"print"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
<span className="code-white">{"parsed"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{"]"}</span><br></br>
<span className="code-white">{"tag"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-blue">{"["}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{"]"}</span><br></br>
<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><br></br>
<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><br></br>
<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-lightyellow">{"True"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"try"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-purple">{"isalpha"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'_\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Ident"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-purple">{"isalpha"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'_\'"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-purple">{"isdigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-purple">{"isdigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Int"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'0\'"}</span>&nbsp;<span className="code-lightyellow">{"and"}</span>&nbsp;<span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'b\'"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'x\'"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-purple">{"isalpha"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-purple">{"isdigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-purple">{"isdigit"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-purple">{"isparen"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Paren"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\'"}</span><span className="code-orange">{"\'"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Str"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span><span className="code-orange">{"\""}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"{str[i]}\""}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\'"}</span><span className="code-orange">{"\'"}</span>&nbsp;<span className="code-lightyellow">{"and"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Escape"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span><span className="code-orange">{"\""}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"{str[i]}\""}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\'"}</span><span className="code-orange">{"\'"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"\'"}</span>&nbsp;<span className="code-lightyellow">{"or"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span><span className="code-orange">{"\""}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"{str[i]}\""}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Paren"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Break"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Str"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"f"}</span><span className="code-orange">{"\""}</span><span className="code-yellow">{"\\\\"}</span><span className="code-orange">{"{str[i]}\""}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'#\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Comment"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-purple">{"ispunct"}</span><span className="code-blue">{"("}</span><span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Etc"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\' \'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Space"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Break"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"str"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\'"}</span><span className="code-yellow">{"\\t"}</span><span className="code-orange">{"\'"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"for"}</span>&nbsp;<span className="code-white">{"j"}</span>&nbsp;<span className="code-magenta">{"in"}</span>&nbsp;<span className="code-purple">{"range"}</span><span className="code-blue">{"("}</span><span className="code-lightgreen">{"0"}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"indentSize"}</span>&nbsp;<span className="code-lightyellow">{"-"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"col"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Space"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"else"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"parsed"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"\""}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"append"}</span><span className="code-blue">{"("}</span><span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-blue">{")"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"col"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"except"}</span>&nbsp;<span className="code-white">{"IndexError"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"break"}</span><br></br>
<br></br>
<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><br></br>
<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-purple">{"checkKeyword"}</span><span className="code-blue">{"("}</span><span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Keyword"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-purple">{"checkBool"}</span><span className="code-blue">{"("}</span><span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span><span className="code-blue">{")"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Etc"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Ident"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"j"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"j"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Space"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"j"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"j"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Paren"}</span>&nbsp;<span className="code-lightyellow">{"and"}</span>&nbsp;<span className="code-white">{"parsed"}</span><span className="code-blue">{"["}</span><span className="code-white">{"j"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-orange">{"\"(\""}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Func"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<br></br>
<span className="code-white">{"file"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-purple">{"open"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"result.js\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-orange">{"\"w\""}</span><span className="code-lightyellow">{","}</span>&nbsp;<span className="code-white">{"encoding"}</span><span className="code-lightyellow">{"="}</span><span className="code-orange">{"\"utf-8\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"<div>"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"0"}</span><br></br>
<span className="code-magenta">{"while"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"!"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Zero"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"if"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Ident"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-white"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Func"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-purple"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Int"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-lightgreen"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Str"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-orange"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Paren"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-blue"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Etc"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-lightyellow"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Keyword"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-magenta"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Space"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"&nbsp;\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Break"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\"<br></br>"}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Comment"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-gray"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-magenta">{"elif"}</span>&nbsp;<span className="code-white">{"tag"}</span><span className="code-blue">{"["}</span><span className="code-white">{"i"}</span><span className="code-blue">{"]"}</span>&nbsp;<span className="code-lightyellow">{"="}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-white">{"Tag"}</span><span className="code-lightyellow">{"."}</span><span className="code-white">{"Escape"}</span><span className="code-lightyellow">{":"}</span><br></br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-white">{"f"}</span><span className="code-orange">{"\"<span className="}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"code-yellow"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{">{{"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"{parsed[i]}"}</span><span className="code-yellow">{"\\\""}</span><span className="code-orange">{"}}</span>\""}</span><span className="code-blue">{")"}</span><br></br>
<br></br>
&nbsp;&nbsp;&nbsp;&nbsp;<span className="code-white">{"i"}</span>&nbsp;<span className="code-lightyellow">{"+"}</span><span className="code-lightyellow">{"="}</span>&nbsp;<span className="code-lightgreen">{"1"}</span><br></br>
<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"write"}</span><span className="code-blue">{"("}</span><span className="code-orange">{"\""}</span><span className="code-yellow">{"\\n"}</span><span className="code-orange">{"</div>\""}</span><span className="code-blue">{")"}</span><br></br>
<span className="code-white">{"file"}</span><span className="code-lightyellow">{"."}</span><span className="code-purple">{"close"}</span><span className="code-blue">{"("}</span><span className="code-blue">{")"}</span><br></br>

</div>
          </div>
        </div>
      </div>
    )
  },
  
  page: function () {
    return (
      <Text title={PythonCodeHighlighter.data.title} createdate={PythonCodeHighlighter.data.createdate} editdate={PythonCodeHighlighter.data.editdate} content={PythonCodeHighlighter.data.content} />
    );
  }  
}

export default PythonCodeHighlighter;